// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Jobstatus struct {
	ID             string
	Name           string
	Command        string
	Args           []string
	Workdir        pgtype.Text
	Timeoutseconds pgtype.Int4
	Status         string
}
